df <- readRDS("Data/summarySCC_PM25.rds")
dfsource <- readRDS("Data/Source_Classification_Code.rds")
sub <- subset(dfsource, dfsource$EI.Sector== c("Mobile - On-Road Gasoline Light Duty Vehicles", "Mobile - On-Road Gasoline Heavy Duty Vehicles", "Mobile - On-Road Diesel Light Duty Vehicles", "Mobile - On-Road Diesel Heavy Duty Vehicles"))
sccneed <- sub[,1]
sccneed <- as.character(sccneed)
subM <- subset(df, df$SCC %in% sccneed)
balt<- subset(subM,subM$fips == "24510")
la<- subset(subM,subM$fips == "06037")
Mean<- tapply(balt$Emissions, balt$year, mean, na.rm=TRUE)
Meanla<- tapply(la$Emissions, la$year, mean, na.rm=TRUE)
balt$year <- as.character(balt$year)
balt$year <- as.numeric(balt$year)
la$year <- as.character(la$year)
la$year <- as.numeric(la$year)
plot(unique(la$year),Meanla, type= "b", main= "Mean Emission over Time, Balt vs La by Motar Vehicles", pch= 19, col= "purple", xlab= "Year", ylim=range( c(Mean, Meanla) ))
points(unique(balt$year),Mean,t="b")
legend("topleft",pch=19, col= c("purple", "black"), legend= c("LA", "Baltimore"))