library(dplyr)
library(ggplot2)
df <- readRDS("Data/summarySCC_PM25.rds")
df$year <- as.factor(df$year)
balt<- subset(df,df$fips=="24510")
tb <- tbl_df(balt)
tb <- tb %>% group_by(year,type)
tplot <- tb %>% summarise(mean(Emissions))
tplot$year <- as.Date(tplot$year, format= "%Y")
p <- qplot(tplot$year,tplot$Emissions, col= tplot$type, xlab = "Year", ylab = "Mean Emission", main="Mean Emission in Baltimore by type of source") 
p + geom_path() + scale_colour_discrete("Types of Source")